# Generated by Django 5.2.5 on 2025-08-16 21:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace_members', '0001_initial'),
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='members',
            field=models.ManyToManyField(related_name='workspaces', through='workspace_members.WorkspaceMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WorkspaceMember',
        ),
    ]
